// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package store

import (
	"context"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO yusui.agents (project_id, role, hostname)
VALUES ($1, $2, $3)
RETURNING id, project_id, role, hostname, netbird_peer_id, netbird_route_id, agent_version, cert_fingerprint, status, last_seen_at, registered_at
`

type CreateAgentParams struct {
	ProjectID int64  `json:"project_id"`
	Role      string `json:"role"`
	Hostname  string `json:"hostname"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (YusuiAgent, error) {
	row := q.db.QueryRow(ctx, createAgent, arg.ProjectID, arg.Role, arg.Hostname)
	var i YusuiAgent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Role,
		&i.Hostname,
		&i.NetbirdPeerID,
		&i.NetbirdRouteID,
		&i.AgentVersion,
		&i.CertFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
	)
	return i, err
}

const getAgentByID = `-- name: GetAgentByID :one
SELECT id, project_id, role, hostname, netbird_peer_id, netbird_route_id, agent_version, cert_fingerprint, status, last_seen_at, registered_at FROM yusui.agents WHERE id = $1
`

func (q *Queries) GetAgentByID(ctx context.Context, id int64) (YusuiAgent, error) {
	row := q.db.QueryRow(ctx, getAgentByID, id)
	var i YusuiAgent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Role,
		&i.Hostname,
		&i.NetbirdPeerID,
		&i.NetbirdRouteID,
		&i.AgentVersion,
		&i.CertFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
	)
	return i, err
}

const getPrimaryAgentForProject = `-- name: GetPrimaryAgentForProject :one
SELECT id, project_id, role, hostname, netbird_peer_id, netbird_route_id, agent_version, cert_fingerprint, status, last_seen_at, registered_at FROM yusui.agents WHERE project_id = $1 AND role = 'primary'
`

func (q *Queries) GetPrimaryAgentForProject(ctx context.Context, projectID int64) (YusuiAgent, error) {
	row := q.db.QueryRow(ctx, getPrimaryAgentForProject, projectID)
	var i YusuiAgent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Role,
		&i.Hostname,
		&i.NetbirdPeerID,
		&i.NetbirdRouteID,
		&i.AgentVersion,
		&i.CertFingerprint,
		&i.Status,
		&i.LastSeenAt,
		&i.RegisteredAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, project_id, role, hostname, netbird_peer_id, netbird_route_id, agent_version, cert_fingerprint, status, last_seen_at, registered_at FROM yusui.agents ORDER BY id
`

func (q *Queries) ListAgents(ctx context.Context) ([]YusuiAgent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAgent
	for rows.Next() {
		var i YusuiAgent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Role,
			&i.Hostname,
			&i.NetbirdPeerID,
			&i.NetbirdRouteID,
			&i.AgentVersion,
			&i.CertFingerprint,
			&i.Status,
			&i.LastSeenAt,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByProject = `-- name: ListAgentsByProject :many
SELECT id, project_id, role, hostname, netbird_peer_id, netbird_route_id, agent_version, cert_fingerprint, status, last_seen_at, registered_at FROM yusui.agents WHERE project_id = $1 ORDER BY id
`

func (q *Queries) ListAgentsByProject(ctx context.Context, projectID int64) ([]YusuiAgent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAgent
	for rows.Next() {
		var i YusuiAgent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Role,
			&i.Hostname,
			&i.NetbirdPeerID,
			&i.NetbirdRouteID,
			&i.AgentVersion,
			&i.CertFingerprint,
			&i.Status,
			&i.LastSeenAt,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAgentStatus = `-- name: SetAgentStatus :exec
UPDATE yusui.agents SET status = $2, last_seen_at = now() WHERE id = $1
`

type SetAgentStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetAgentStatus(ctx context.Context, arg SetAgentStatusParams) error {
	_, err := q.db.Exec(ctx, setAgentStatus, arg.ID, arg.Status)
	return err
}
