// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: asset_credentials.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetCredential = `-- name: CreateAssetCredential :one
INSERT INTO yusui.asset_credentials
  (asset_id, ssh_user, auth_kind, secret_enc, secret_kms_key_id, fingerprint, description)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, asset_id, ssh_user, auth_kind, secret_kms_key_id, fingerprint, description, created_at, rotated_at, is_active
`

type CreateAssetCredentialParams struct {
	AssetID        int64   `json:"asset_id"`
	SshUser        string  `json:"ssh_user"`
	AuthKind       string  `json:"auth_kind"`
	SecretEnc      []byte  `json:"secret_enc"`
	SecretKmsKeyID string  `json:"secret_kms_key_id"`
	Fingerprint    *string `json:"fingerprint"`
	Description    *string `json:"description"`
}

type CreateAssetCredentialRow struct {
	ID             int64              `json:"id"`
	AssetID        int64              `json:"asset_id"`
	SshUser        string             `json:"ssh_user"`
	AuthKind       string             `json:"auth_kind"`
	SecretKmsKeyID string             `json:"secret_kms_key_id"`
	Fingerprint    *string            `json:"fingerprint"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RotatedAt      pgtype.Timestamptz `json:"rotated_at"`
	IsActive       bool               `json:"is_active"`
}

func (q *Queries) CreateAssetCredential(ctx context.Context, arg CreateAssetCredentialParams) (CreateAssetCredentialRow, error) {
	row := q.db.QueryRow(ctx, createAssetCredential,
		arg.AssetID,
		arg.SshUser,
		arg.AuthKind,
		arg.SecretEnc,
		arg.SecretKmsKeyID,
		arg.Fingerprint,
		arg.Description,
	)
	var i CreateAssetCredentialRow
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.SshUser,
		&i.AuthKind,
		&i.SecretKmsKeyID,
		&i.Fingerprint,
		&i.Description,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.IsActive,
	)
	return i, err
}

const getActiveCredentialForAsset = `-- name: GetActiveCredentialForAsset :one
SELECT id, asset_id, ssh_user, auth_kind, secret_enc, secret_kms_key_id, fingerprint, description, created_at, rotated_at, is_active FROM yusui.asset_credentials
WHERE asset_id = $1 AND is_active = TRUE
ORDER BY id DESC
LIMIT 1
`

// Returns the full row including secret_enc (Web Shell decrypts in-process).
func (q *Queries) GetActiveCredentialForAsset(ctx context.Context, assetID int64) (YusuiAssetCredential, error) {
	row := q.db.QueryRow(ctx, getActiveCredentialForAsset, assetID)
	var i YusuiAssetCredential
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.SshUser,
		&i.AuthKind,
		&i.SecretEnc,
		&i.SecretKmsKeyID,
		&i.Fingerprint,
		&i.Description,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.IsActive,
	)
	return i, err
}

const listCredentialsForAsset = `-- name: ListCredentialsForAsset :many
SELECT id, asset_id, ssh_user, auth_kind, secret_kms_key_id, fingerprint, description, created_at, rotated_at, is_active
FROM yusui.asset_credentials
WHERE asset_id = $1
ORDER BY id
`

type ListCredentialsForAssetRow struct {
	ID             int64              `json:"id"`
	AssetID        int64              `json:"asset_id"`
	SshUser        string             `json:"ssh_user"`
	AuthKind       string             `json:"auth_kind"`
	SecretKmsKeyID string             `json:"secret_kms_key_id"`
	Fingerprint    *string            `json:"fingerprint"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RotatedAt      pgtype.Timestamptz `json:"rotated_at"`
	IsActive       bool               `json:"is_active"`
}

// Excludes secret_enc — never list secrets.
func (q *Queries) ListCredentialsForAsset(ctx context.Context, assetID int64) ([]ListCredentialsForAssetRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsForAssetRow
	for rows.Next() {
		var i ListCredentialsForAssetRow
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.SshUser,
			&i.AuthKind,
			&i.SecretKmsKeyID,
			&i.Fingerprint,
			&i.Description,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
