// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package store

import (
	"context"
	"net/netip"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO yusui.assets (project_id, name, ip_internal, ports, os, tags)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, name, ip_internal, ports, os, tags, source, created_at, command_policy_id
`

type CreateAssetParams struct {
	ProjectID  int64      `json:"project_id"`
	Name       string     `json:"name"`
	IpInternal netip.Addr `json:"ip_internal"`
	Ports      []int32    `json:"ports"`
	Os         *string    `json:"os"`
	Tags       []byte     `json:"tags"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (YusuiAsset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ProjectID,
		arg.Name,
		arg.IpInternal,
		arg.Ports,
		arg.Os,
		arg.Tags,
	)
	var i YusuiAsset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IpInternal,
		&i.Ports,
		&i.Os,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.CommandPolicyID,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, project_id, name, ip_internal, ports, os, tags, source, created_at, command_policy_id FROM yusui.assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id int64) (YusuiAsset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i YusuiAsset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.IpInternal,
		&i.Ports,
		&i.Os,
		&i.Tags,
		&i.Source,
		&i.CreatedAt,
		&i.CommandPolicyID,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, project_id, name, ip_internal, ports, os, tags, source, created_at, command_policy_id FROM yusui.assets ORDER BY id
`

func (q *Queries) ListAssets(ctx context.Context) ([]YusuiAsset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAsset
	for rows.Next() {
		var i YusuiAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IpInternal,
			&i.Ports,
			&i.Os,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.CommandPolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByIDs = `-- name: ListAssetsByIDs :many
SELECT id, project_id, name, ip_internal, ports, os, tags, source, created_at, command_policy_id FROM yusui.assets WHERE id = ANY($1::bigint[]) ORDER BY id
`

func (q *Queries) ListAssetsByIDs(ctx context.Context, ids []int64) ([]YusuiAsset, error) {
	rows, err := q.db.Query(ctx, listAssetsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAsset
	for rows.Next() {
		var i YusuiAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IpInternal,
			&i.Ports,
			&i.Os,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.CommandPolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByProject = `-- name: ListAssetsByProject :many
SELECT id, project_id, name, ip_internal, ports, os, tags, source, created_at, command_policy_id FROM yusui.assets WHERE project_id = $1 ORDER BY id
`

func (q *Queries) ListAssetsByProject(ctx context.Context, projectID int64) ([]YusuiAsset, error) {
	rows, err := q.db.Query(ctx, listAssetsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAsset
	for rows.Next() {
		var i YusuiAsset
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.IpInternal,
			&i.Ports,
			&i.Os,
			&i.Tags,
			&i.Source,
			&i.CreatedAt,
			&i.CommandPolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
