// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package store

import (
	"context"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO yusui.audit_logs (actor_type, actor_id, action, target_type, target_id, payload)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	ActorType  string  `json:"actor_type"`
	ActorID    *string `json:"actor_id"`
	Action     string  `json:"action"`
	TargetType *string `json:"target_type"`
	TargetID   *string `json:"target_id"`
	Payload    []byte  `json:"payload"`
}

// Append-only (yusui_app has INSERT only on this table — invariant #7).
func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Payload,
	)
	return err
}

const listAuditByTarget = `-- name: ListAuditByTarget :many
SELECT id, ts, actor_type, actor_id, action, target_type, target_id, payload, prev_hash, hash FROM yusui.audit_logs
WHERE target_type = $1 AND target_id = $2
ORDER BY ts DESC, id DESC
LIMIT $3
`

type ListAuditByTargetParams struct {
	TargetType *string `json:"target_type"`
	TargetID   *string `json:"target_id"`
	Limit      int32   `json:"limit"`
}

func (q *Queries) ListAuditByTarget(ctx context.Context, arg ListAuditByTargetParams) ([]YusuiAuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditByTarget, arg.TargetType, arg.TargetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAuditLog
	for rows.Next() {
		var i YusuiAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAudit = `-- name: ListRecentAudit :many
SELECT id, ts, actor_type, actor_id, action, target_type, target_id, payload, prev_hash, hash FROM yusui.audit_logs ORDER BY ts DESC, id DESC LIMIT $1
`

func (q *Queries) ListRecentAudit(ctx context.Context, limit int32) ([]YusuiAuditLog, error) {
	rows, err := q.db.Query(ctx, listRecentAudit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiAuditLog
	for rows.Next() {
		var i YusuiAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
