// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type YusuiAgent struct {
	ID              int64              `json:"id"`
	ProjectID       int64              `json:"project_id"`
	Role            string             `json:"role"`
	Hostname        string             `json:"hostname"`
	NetbirdPeerID   *string            `json:"netbird_peer_id"`
	NetbirdRouteID  *string            `json:"netbird_route_id"`
	AgentVersion    *string            `json:"agent_version"`
	CertFingerprint *string            `json:"cert_fingerprint"`
	Status          string             `json:"status"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	RegisteredAt    pgtype.Timestamptz `json:"registered_at"`
}

type YusuiAsset struct {
	ID              int64              `json:"id"`
	ProjectID       int64              `json:"project_id"`
	Name            string             `json:"name"`
	IpInternal      netip.Addr         `json:"ip_internal"`
	Ports           []int32            `json:"ports"`
	Os              *string            `json:"os"`
	Tags            []byte             `json:"tags"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CommandPolicyID *int64             `json:"command_policy_id"`
}

type YusuiAssetCredential struct {
	ID             int64              `json:"id"`
	AssetID        int64              `json:"asset_id"`
	SshUser        string             `json:"ssh_user"`
	AuthKind       string             `json:"auth_kind"`
	SecretEnc      []byte             `json:"secret_enc"`
	SecretKmsKeyID string             `json:"secret_kms_key_id"`
	Fingerprint    *string            `json:"fingerprint"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	RotatedAt      pgtype.Timestamptz `json:"rotated_at"`
	IsActive       bool               `json:"is_active"`
}

type YusuiAuditLog struct {
	ID         int64              `json:"id"`
	Ts         pgtype.Timestamptz `json:"ts"`
	ActorType  string             `json:"actor_type"`
	ActorID    *string            `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType *string            `json:"target_type"`
	TargetID   *string            `json:"target_id"`
	Payload    []byte             `json:"payload"`
	PrevHash   []byte             `json:"prev_hash"`
	Hash       []byte             `json:"hash"`
}

type YusuiCommandFilterEvent struct {
	ID            int64              `json:"id"`
	SessionID     int64              `json:"session_id"`
	Ts            pgtype.Timestamptz `json:"ts"`
	RuleID        string             `json:"rule_id"`
	Severity      string             `json:"severity"`
	ActionTaken   string             `json:"action_taken"`
	Source        string             `json:"source"`
	AttacherLabel *string            `json:"attacher_label"`
	RawLine       string             `json:"raw_line"`
}

type YusuiCommandPolicy struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	IsBuiltin bool               `json:"is_builtin"`
	Rules     []byte             `json:"rules"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type YusuiNetbirdGlobalSetting struct {
	ID                int16              `json:"id"`
	ServerPeerID      string             `json:"server_peer_id"`
	ServerPeerGroupID string             `json:"server_peer_group_id"`
	BuiltinPolicyID   string             `json:"builtin_policy_id"`
	InstalledAt       pgtype.Timestamptz `json:"installed_at"`
	LastReconciledAt  pgtype.Timestamptz `json:"last_reconciled_at"`
}

type YusuiPolicyBinding struct {
	TicketID       int64              `json:"ticket_id"`
	AgentID        int64              `json:"agent_id"`
	AgentRuleID    string             `json:"agent_rule_id"`
	SrcPeerIps     []netip.Addr       `json:"src_peer_ips"`
	AgentAppliedAt pgtype.Timestamptz `json:"agent_applied_at"`
	ApplyAttempts  int32              `json:"apply_attempts"`
	RevokeAttempts int32              `json:"revoke_attempts"`
	LastError      *string            `json:"last_error"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type YusuiProject struct {
	ID              int64              `json:"id"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Cidrs           []netip.Prefix     `json:"cidrs"`
	NetbirdGroupID  *string            `json:"netbird_group_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CommandPolicyID *int64             `json:"command_policy_id"`
}

type YusuiSession struct {
	ID                    int64              `json:"id"`
	PubID                 string             `json:"pub_id"`
	TicketID              int64              `json:"ticket_id"`
	AssetID               int64              `json:"asset_id"`
	AgentID               int64              `json:"agent_id"`
	SshUser               string             `json:"ssh_user"`
	Status                string             `json:"status"`
	OpenedAt              pgtype.Timestamptz `json:"opened_at"`
	ClosedAt              pgtype.Timestamptz `json:"closed_at"`
	ClosedReason          *string            `json:"closed_reason"`
	RecordingUri          *string            `json:"recording_uri"`
	CommandPolicySnapshot []byte             `json:"command_policy_snapshot"`
}

type YusuiSessionAttacher struct {
	ID         int64              `json:"id"`
	SessionID  int64              `json:"session_id"`
	UserID     *int64             `json:"user_id"`
	Source     string             `json:"source"`
	Label      *string            `json:"label"`
	Role       string             `json:"role"`
	AttachedAt pgtype.Timestamptz `json:"attached_at"`
	DetachedAt pgtype.Timestamptz `json:"detached_at"`
}

type YusuiTicket struct {
	ID             int64              `json:"id"`
	PubID          string             `json:"pub_id"`
	RequesterID    int64              `json:"requester_id"`
	ApproverID     *int64             `json:"approver_id"`
	ProjectID      int64              `json:"project_id"`
	TargetSelector []byte             `json:"target_selector"`
	FrozenAssetIds []int64            `json:"frozen_asset_ids"`
	Ports          []int32            `json:"ports"`
	Protocol       string             `json:"protocol"`
	AccessKind     string             `json:"access_kind"`
	Reason         string             `json:"reason"`
	DurationSec    int32              `json:"duration_sec"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ApprovedAt     pgtype.Timestamptz `json:"approved_at"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type YusuiUser struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	DisplayName       *string            `json:"display_name"`
	Email             *string            `json:"email"`
	Role              string             `json:"role"`
	PasswordHash      *string            `json:"password_hash"`
	PasswordAlg       string             `json:"password_alg"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	MfaSecretEnc      []byte             `json:"mfa_secret_enc"`
	MfaEnabled        bool               `json:"mfa_enabled"`
	FailedLoginCount  int32              `json:"failed_login_count"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	ExternalID        *string            `json:"external_id"`
	ExternalIssuer    *string            `json:"external_issuer"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
