// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy_bindings.sql

package store

import (
	"context"
	"net/netip"
)

const getBinding = `-- name: GetBinding :one
SELECT ticket_id, agent_id, agent_rule_id, src_peer_ips, agent_applied_at, apply_attempts, revoke_attempts, last_error, updated_at FROM yusui.policy_bindings WHERE ticket_id = $1
`

func (q *Queries) GetBinding(ctx context.Context, ticketID int64) (YusuiPolicyBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, ticketID)
	var i YusuiPolicyBinding
	err := row.Scan(
		&i.TicketID,
		&i.AgentID,
		&i.AgentRuleID,
		&i.SrcPeerIps,
		&i.AgentAppliedAt,
		&i.ApplyAttempts,
		&i.RevokeAttempts,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const setBindingApplied = `-- name: SetBindingApplied :exec
UPDATE yusui.policy_bindings
SET agent_applied_at = now(), apply_attempts = apply_attempts + 1, updated_at = now()
WHERE ticket_id = $1
`

func (q *Queries) SetBindingApplied(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, setBindingApplied, ticketID)
	return err
}

const upsertBinding = `-- name: UpsertBinding :exec
INSERT INTO yusui.policy_bindings (ticket_id, agent_id, agent_rule_id, src_peer_ips)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ticket_id) DO UPDATE
SET agent_id = excluded.agent_id,
    agent_rule_id = excluded.agent_rule_id,
    src_peer_ips = excluded.src_peer_ips,
    updated_at = now()
`

type UpsertBindingParams struct {
	TicketID    int64        `json:"ticket_id"`
	AgentID     int64        `json:"agent_id"`
	AgentRuleID string       `json:"agent_rule_id"`
	SrcPeerIps  []netip.Addr `json:"src_peer_ips"`
}

func (q *Queries) UpsertBinding(ctx context.Context, arg UpsertBindingParams) error {
	_, err := q.db.Exec(ctx, upsertBinding,
		arg.TicketID,
		arg.AgentID,
		arg.AgentRuleID,
		arg.SrcPeerIps,
	)
	return err
}
