// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"
	"net/netip"
)

const createProject = `-- name: CreateProject :one
INSERT INTO yusui.projects (code, name, cidrs)
VALUES ($1, $2, $3)
RETURNING id, code, name, cidrs, netbird_group_id, created_at, command_policy_id
`

type CreateProjectParams struct {
	Code  string         `json:"code"`
	Name  string         `json:"name"`
	Cidrs []netip.Prefix `json:"cidrs"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (YusuiProject, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Code, arg.Name, arg.Cidrs)
	var i YusuiProject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Cidrs,
		&i.NetbirdGroupID,
		&i.CreatedAt,
		&i.CommandPolicyID,
	)
	return i, err
}

const getProjectByCode = `-- name: GetProjectByCode :one
SELECT id, code, name, cidrs, netbird_group_id, created_at, command_policy_id FROM yusui.projects WHERE code = $1
`

func (q *Queries) GetProjectByCode(ctx context.Context, code string) (YusuiProject, error) {
	row := q.db.QueryRow(ctx, getProjectByCode, code)
	var i YusuiProject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Cidrs,
		&i.NetbirdGroupID,
		&i.CreatedAt,
		&i.CommandPolicyID,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, code, name, cidrs, netbird_group_id, created_at, command_policy_id FROM yusui.projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (YusuiProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i YusuiProject
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Cidrs,
		&i.NetbirdGroupID,
		&i.CreatedAt,
		&i.CommandPolicyID,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, code, name, cidrs, netbird_group_id, created_at, command_policy_id FROM yusui.projects ORDER BY id
`

func (q *Queries) ListProjects(ctx context.Context) ([]YusuiProject, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiProject
	for rows.Next() {
		var i YusuiProject
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Cidrs,
			&i.NetbirdGroupID,
			&i.CreatedAt,
			&i.CommandPolicyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
