// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
)

const addAttacher = `-- name: AddAttacher :one
INSERT INTO yusui.session_attachers (session_id, user_id, source, label, role, attached_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id
`

type AddAttacherParams struct {
	SessionID int64   `json:"session_id"`
	UserID    *int64  `json:"user_id"`
	Source    string  `json:"source"`
	Label     *string `json:"label"`
	Role      string  `json:"role"`
}

func (q *Queries) AddAttacher(ctx context.Context, arg AddAttacherParams) (int64, error) {
	row := q.db.QueryRow(ctx, addAttacher,
		arg.SessionID,
		arg.UserID,
		arg.Source,
		arg.Label,
		arg.Role,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const closeSession = `-- name: CloseSession :exec
UPDATE yusui.sessions
SET status = 'closed', closed_at = now(), closed_reason = $2, recording_uri = $3
WHERE id = $1 AND status <> 'closed'
`

type CloseSessionParams struct {
	ID           int64   `json:"id"`
	ClosedReason *string `json:"closed_reason"`
	RecordingUri *string `json:"recording_uri"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) error {
	_, err := q.db.Exec(ctx, closeSession, arg.ID, arg.ClosedReason, arg.RecordingUri)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO yusui.sessions (pub_id, ticket_id, asset_id, agent_id, ssh_user, status, command_policy_snapshot)
VALUES ($1, $2, $3, $4, $5, 'allocated', $6)
RETURNING id, pub_id, ticket_id, asset_id, agent_id, ssh_user, status, opened_at, closed_at, closed_reason, recording_uri, command_policy_snapshot
`

type CreateSessionParams struct {
	PubID                 string `json:"pub_id"`
	TicketID              int64  `json:"ticket_id"`
	AssetID               int64  `json:"asset_id"`
	AgentID               int64  `json:"agent_id"`
	SshUser               string `json:"ssh_user"`
	CommandPolicySnapshot []byte `json:"command_policy_snapshot"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (YusuiSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.PubID,
		arg.TicketID,
		arg.AssetID,
		arg.AgentID,
		arg.SshUser,
		arg.CommandPolicySnapshot,
	)
	var i YusuiSession
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.TicketID,
		&i.AssetID,
		&i.AgentID,
		&i.SshUser,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.RecordingUri,
		&i.CommandPolicySnapshot,
	)
	return i, err
}

const detachAttacher = `-- name: DetachAttacher :exec
UPDATE yusui.session_attachers SET detached_at = now() WHERE id = $1
`

func (q *Queries) DetachAttacher(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, detachAttacher, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, pub_id, ticket_id, asset_id, agent_id, ssh_user, status, opened_at, closed_at, closed_reason, recording_uri, command_policy_snapshot FROM yusui.sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (YusuiSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i YusuiSession
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.TicketID,
		&i.AssetID,
		&i.AgentID,
		&i.SshUser,
		&i.Status,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.ClosedReason,
		&i.RecordingUri,
		&i.CommandPolicySnapshot,
	)
	return i, err
}

const insertCommandFilterEvent = `-- name: InsertCommandFilterEvent :exec
INSERT INTO yusui.command_filter_events
  (session_id, rule_id, severity, action_taken, source, attacher_label, raw_line)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertCommandFilterEventParams struct {
	SessionID     int64   `json:"session_id"`
	RuleID        string  `json:"rule_id"`
	Severity      string  `json:"severity"`
	ActionTaken   string  `json:"action_taken"`
	Source        string  `json:"source"`
	AttacherLabel *string `json:"attacher_label"`
	RawLine       string  `json:"raw_line"`
}

func (q *Queries) InsertCommandFilterEvent(ctx context.Context, arg InsertCommandFilterEventParams) error {
	_, err := q.db.Exec(ctx, insertCommandFilterEvent,
		arg.SessionID,
		arg.RuleID,
		arg.Severity,
		arg.ActionTaken,
		arg.Source,
		arg.AttacherLabel,
		arg.RawLine,
	)
	return err
}

const listSessionsByTicket = `-- name: ListSessionsByTicket :many
SELECT id, pub_id, ticket_id, asset_id, agent_id, ssh_user, status, opened_at, closed_at, closed_reason, recording_uri, command_policy_snapshot FROM yusui.sessions WHERE ticket_id = $1 ORDER BY id DESC
`

func (q *Queries) ListSessionsByTicket(ctx context.Context, ticketID int64) ([]YusuiSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByTicket, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiSession
	for rows.Next() {
		var i YusuiSession
		if err := rows.Scan(
			&i.ID,
			&i.PubID,
			&i.TicketID,
			&i.AssetID,
			&i.AgentID,
			&i.SshUser,
			&i.Status,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.ClosedReason,
			&i.RecordingUri,
			&i.CommandPolicySnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionRunning = `-- name: SetSessionRunning :exec
UPDATE yusui.sessions SET status = 'running', opened_at = now() WHERE id = $1
`

func (q *Queries) SetSessionRunning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, setSessionRunning, id)
	return err
}
