// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeTicket = `-- name: CloseTicket :exec
UPDATE yusui.tickets SET status = $2, closed_at = now(), updated_at = now() WHERE id = $1
`

type CloseTicketParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) CloseTicket(ctx context.Context, arg CloseTicketParams) error {
	_, err := q.db.Exec(ctx, closeTicket, arg.ID, arg.Status)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO yusui.tickets
  (pub_id, requester_id, project_id, target_selector, ports, protocol, access_kind, reason, duration_sec, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending')
RETURNING id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at
`

type CreateTicketParams struct {
	PubID          string  `json:"pub_id"`
	RequesterID    int64   `json:"requester_id"`
	ProjectID      int64   `json:"project_id"`
	TargetSelector []byte  `json:"target_selector"`
	Ports          []int32 `json:"ports"`
	Protocol       string  `json:"protocol"`
	AccessKind     string  `json:"access_kind"`
	Reason         string  `json:"reason"`
	DurationSec    int32   `json:"duration_sec"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (YusuiTicket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.PubID,
		arg.RequesterID,
		arg.ProjectID,
		arg.TargetSelector,
		arg.Ports,
		arg.Protocol,
		arg.AccessKind,
		arg.Reason,
		arg.DurationSec,
	)
	var i YusuiTicket
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.RequesterID,
		&i.ApproverID,
		&i.ProjectID,
		&i.TargetSelector,
		&i.FrozenAssetIds,
		&i.Ports,
		&i.Protocol,
		&i.AccessKind,
		&i.Reason,
		&i.DurationSec,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id int64) (YusuiTicket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i YusuiTicket
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.RequesterID,
		&i.ApproverID,
		&i.ProjectID,
		&i.TargetSelector,
		&i.FrozenAssetIds,
		&i.Ports,
		&i.Protocol,
		&i.AccessKind,
		&i.Reason,
		&i.DurationSec,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByPubID = `-- name: GetTicketByPubID :one
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets WHERE pub_id = $1
`

func (q *Queries) GetTicketByPubID(ctx context.Context, pubID string) (YusuiTicket, error) {
	row := q.db.QueryRow(ctx, getTicketByPubID, pubID)
	var i YusuiTicket
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.RequesterID,
		&i.ApproverID,
		&i.ProjectID,
		&i.TargetSelector,
		&i.FrozenAssetIds,
		&i.Ports,
		&i.Protocol,
		&i.AccessKind,
		&i.Reason,
		&i.DurationSec,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketForUpdate = `-- name: GetTicketForUpdate :one
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTicketForUpdate(ctx context.Context, id int64) (YusuiTicket, error) {
	row := q.db.QueryRow(ctx, getTicketForUpdate, id)
	var i YusuiTicket
	err := row.Scan(
		&i.ID,
		&i.PubID,
		&i.RequesterID,
		&i.ApproverID,
		&i.ProjectID,
		&i.TargetSelector,
		&i.FrozenAssetIds,
		&i.Ports,
		&i.Protocol,
		&i.AccessKind,
		&i.Reason,
		&i.DurationSec,
		&i.Status,
		&i.CreatedAt,
		&i.ApprovedAt,
		&i.ActivatedAt,
		&i.ExpiresAt,
		&i.ClosedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTickets = `-- name: ListActiveTickets :many
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets
WHERE status = 'active' AND (expires_at IS NULL OR expires_at > now())
ORDER BY id
`

// Not-yet-expired active tickets — used to rebuild the in-memory forward map
// after a Server restart (docs/10).
func (q *Queries) ListActiveTickets(ctx context.Context) ([]YusuiTicket, error) {
	rows, err := q.db.Query(ctx, listActiveTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiTicket
	for rows.Next() {
		var i YusuiTicket
		if err := rows.Scan(
			&i.ID,
			&i.PubID,
			&i.RequesterID,
			&i.ApproverID,
			&i.ProjectID,
			&i.TargetSelector,
			&i.FrozenAssetIds,
			&i.Ports,
			&i.Protocol,
			&i.AccessKind,
			&i.Reason,
			&i.DurationSec,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveTickets = `-- name: ListExpiredActiveTickets :many
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets
WHERE status = 'active' AND expires_at IS NOT NULL AND expires_at <= now()
ORDER BY id
`

func (q *Queries) ListExpiredActiveTickets(ctx context.Context) ([]YusuiTicket, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiTicket
	for rows.Next() {
		var i YusuiTicket
		if err := rows.Scan(
			&i.ID,
			&i.PubID,
			&i.RequesterID,
			&i.ApproverID,
			&i.ProjectID,
			&i.TargetSelector,
			&i.FrozenAssetIds,
			&i.Ports,
			&i.Protocol,
			&i.AccessKind,
			&i.Reason,
			&i.DurationSec,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets ORDER BY id DESC
`

func (q *Queries) ListTickets(ctx context.Context) ([]YusuiTicket, error) {
	rows, err := q.db.Query(ctx, listTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiTicket
	for rows.Next() {
		var i YusuiTicket
		if err := rows.Scan(
			&i.ID,
			&i.PubID,
			&i.RequesterID,
			&i.ApproverID,
			&i.ProjectID,
			&i.TargetSelector,
			&i.FrozenAssetIds,
			&i.Ports,
			&i.Protocol,
			&i.AccessKind,
			&i.Reason,
			&i.DurationSec,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByRequester = `-- name: ListTicketsByRequester :many
SELECT id, pub_id, requester_id, approver_id, project_id, target_selector, frozen_asset_ids, ports, protocol, access_kind, reason, duration_sec, status, created_at, approved_at, activated_at, expires_at, closed_at, updated_at FROM yusui.tickets WHERE requester_id = $1 ORDER BY id DESC
`

func (q *Queries) ListTicketsByRequester(ctx context.Context, requesterID int64) ([]YusuiTicket, error) {
	rows, err := q.db.Query(ctx, listTicketsByRequester, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YusuiTicket
	for rows.Next() {
		var i YusuiTicket
		if err := rows.Scan(
			&i.ID,
			&i.PubID,
			&i.RequesterID,
			&i.ApproverID,
			&i.ProjectID,
			&i.TargetSelector,
			&i.FrozenAssetIds,
			&i.Ports,
			&i.Protocol,
			&i.AccessKind,
			&i.Reason,
			&i.DurationSec,
			&i.Status,
			&i.CreatedAt,
			&i.ApprovedAt,
			&i.ActivatedAt,
			&i.ExpiresAt,
			&i.ClosedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTicketActive = `-- name: SetTicketActive :exec
UPDATE yusui.tickets
SET status = 'active', activated_at = now(), expires_at = $2, updated_at = now()
WHERE id = $1
`

type SetTicketActiveParams struct {
	ID        int64              `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) SetTicketActive(ctx context.Context, arg SetTicketActiveParams) error {
	_, err := q.db.Exec(ctx, setTicketActive, arg.ID, arg.ExpiresAt)
	return err
}

const setTicketApproved = `-- name: SetTicketApproved :exec
UPDATE yusui.tickets
SET approver_id = $2, approved_at = now(), frozen_asset_ids = $3, status = 'approved', updated_at = now()
WHERE id = $1
`

type SetTicketApprovedParams struct {
	ID             int64   `json:"id"`
	ApproverID     *int64  `json:"approver_id"`
	FrozenAssetIds []int64 `json:"frozen_asset_ids"`
}

func (q *Queries) SetTicketApproved(ctx context.Context, arg SetTicketApprovedParams) error {
	_, err := q.db.Exec(ctx, setTicketApproved, arg.ID, arg.ApproverID, arg.FrozenAssetIds)
	return err
}

const setTicketStatus = `-- name: SetTicketStatus :exec
UPDATE yusui.tickets SET status = $2, updated_at = now() WHERE id = $1
`

type SetTicketStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) error {
	_, err := q.db.Exec(ctx, setTicketStatus, arg.ID, arg.Status)
	return err
}
