// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM yusui.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO yusui.users (username, display_name, email, role, password_hash, mfa_secret_enc, mfa_enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, display_name, email, role, password_hash, password_alg, password_changed_at, mfa_secret_enc, mfa_enabled, failed_login_count, locked_until, last_login_at, external_id, external_issuer, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string  `json:"username"`
	DisplayName  *string `json:"display_name"`
	Email        *string `json:"email"`
	Role         string  `json:"role"`
	PasswordHash *string `json:"password_hash"`
	MfaSecretEnc []byte  `json:"mfa_secret_enc"`
	MfaEnabled   bool    `json:"mfa_enabled"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (YusuiUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.Email,
		arg.Role,
		arg.PasswordHash,
		arg.MfaSecretEnc,
		arg.MfaEnabled,
	)
	var i YusuiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordAlg,
		&i.PasswordChangedAt,
		&i.MfaSecretEnc,
		&i.MfaEnabled,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.ExternalID,
		&i.ExternalIssuer,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, email, role, password_hash, password_alg, password_changed_at, mfa_secret_enc, mfa_enabled, failed_login_count, locked_until, last_login_at, external_id, external_issuer, is_active, created_at, updated_at FROM yusui.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (YusuiUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i YusuiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordAlg,
		&i.PasswordChangedAt,
		&i.MfaSecretEnc,
		&i.MfaEnabled,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.ExternalID,
		&i.ExternalIssuer,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, email, role, password_hash, password_alg, password_changed_at, mfa_secret_enc, mfa_enabled, failed_login_count, locked_until, last_login_at, external_id, external_issuer, is_active, created_at, updated_at FROM yusui.users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (YusuiUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i YusuiUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Role,
		&i.PasswordHash,
		&i.PasswordAlg,
		&i.PasswordChangedAt,
		&i.MfaSecretEnc,
		&i.MfaEnabled,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.ExternalID,
		&i.ExternalIssuer,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, email, role, mfa_enabled, is_active, last_login_at, created_at
FROM yusui.users ORDER BY id
`

type ListUsersRow struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	Email       *string            `json:"email"`
	Role        string             `json:"role"`
	MfaEnabled  bool               `json:"mfa_enabled"`
	IsActive    bool               `json:"is_active"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Excludes password_hash / mfa_secret_enc — never list secrets.
func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Role,
			&i.MfaEnabled,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoginFailure = `-- name: MarkLoginFailure :one
UPDATE yusui.users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE WHEN failed_login_count + 1 >= 5 THEN now() + interval '15 minutes' ELSE locked_until END,
    updated_at = now()
WHERE id = $1
RETURNING failed_login_count, locked_until
`

type MarkLoginFailureRow struct {
	FailedLoginCount int32              `json:"failed_login_count"`
	LockedUntil      pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) MarkLoginFailure(ctx context.Context, id int64) (MarkLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, markLoginFailure, id)
	var i MarkLoginFailureRow
	err := row.Scan(&i.FailedLoginCount, &i.LockedUntil)
	return i, err
}

const markLoginSuccess = `-- name: MarkLoginSuccess :exec
UPDATE yusui.users
SET last_login_at = now(), failed_login_count = 0, locked_until = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkLoginSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markLoginSuccess, id)
	return err
}
