// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: yusui/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_READY       AgentStatus = 1
	AgentStatus_AGENT_STATUS_DEGRADED    AgentStatus = 2
	AgentStatus_AGENT_STATUS_FROZEN      AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_READY",
		2: "AGENT_STATUS_DEGRADED",
		3: "AGENT_STATUS_FROZEN",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_READY":       1,
		"AGENT_STATUS_DEGRADED":    2,
		"AGENT_STATUS_FROZEN":      3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_yusui_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_yusui_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type AckResult int32

const (
	AckResult_ACK_RESULT_UNSPECIFIED AckResult = 0
	AckResult_ACK_RESULT_OK          AckResult = 1
	AckResult_ACK_RESULT_FAILED      AckResult = 2
	AckResult_ACK_RESULT_PARTIAL     AckResult = 3
	AckResult_ACK_RESULT_SKIPPED     AckResult = 4
)

// Enum value maps for AckResult.
var (
	AckResult_name = map[int32]string{
		0: "ACK_RESULT_UNSPECIFIED",
		1: "ACK_RESULT_OK",
		2: "ACK_RESULT_FAILED",
		3: "ACK_RESULT_PARTIAL",
		4: "ACK_RESULT_SKIPPED",
	}
	AckResult_value = map[string]int32{
		"ACK_RESULT_UNSPECIFIED": 0,
		"ACK_RESULT_OK":          1,
		"ACK_RESULT_FAILED":      2,
		"ACK_RESULT_PARTIAL":     3,
		"ACK_RESULT_SKIPPED":     4,
	}
)

func (x AckResult) Enum() *AckResult {
	p := new(AckResult)
	*p = x
	return p
}

func (x AckResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckResult) Descriptor() protoreflect.EnumDescriptor {
	return file_yusui_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (AckResult) Type() protoreflect.EnumType {
	return &file_yusui_agent_v1_agent_proto_enumTypes[1]
}

func (x AckResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckResult.Descriptor instead.
func (AckResult) EnumDescriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type RuleEventKind int32

const (
	RuleEventKind_RULE_EVENT_KIND_UNSPECIFIED   RuleEventKind = 0
	RuleEventKind_RULE_EVENT_KIND_APPLIED       RuleEventKind = 1
	RuleEventKind_RULE_EVENT_KIND_REVOKED       RuleEventKind = 2
	RuleEventKind_RULE_EVENT_KIND_EXPIRED_LOCAL RuleEventKind = 3
	RuleEventKind_RULE_EVENT_KIND_HIT_FIRST     RuleEventKind = 4
	RuleEventKind_RULE_EVENT_KIND_HIT_LAST      RuleEventKind = 5
)

// Enum value maps for RuleEventKind.
var (
	RuleEventKind_name = map[int32]string{
		0: "RULE_EVENT_KIND_UNSPECIFIED",
		1: "RULE_EVENT_KIND_APPLIED",
		2: "RULE_EVENT_KIND_REVOKED",
		3: "RULE_EVENT_KIND_EXPIRED_LOCAL",
		4: "RULE_EVENT_KIND_HIT_FIRST",
		5: "RULE_EVENT_KIND_HIT_LAST",
	}
	RuleEventKind_value = map[string]int32{
		"RULE_EVENT_KIND_UNSPECIFIED":   0,
		"RULE_EVENT_KIND_APPLIED":       1,
		"RULE_EVENT_KIND_REVOKED":       2,
		"RULE_EVENT_KIND_EXPIRED_LOCAL": 3,
		"RULE_EVENT_KIND_HIT_FIRST":     4,
		"RULE_EVENT_KIND_HIT_LAST":      5,
	}
)

func (x RuleEventKind) Enum() *RuleEventKind {
	p := new(RuleEventKind)
	*p = x
	return p
}

func (x RuleEventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleEventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_yusui_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (RuleEventKind) Type() protoreflect.EnumType {
	return &file_yusui_agent_v1_agent_proto_enumTypes[2]
}

func (x RuleEventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleEventKind.Descriptor instead.
func (RuleEventKind) EnumDescriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type Protocol int32

const (
	Protocol_PROTOCOL_UNSPECIFIED Protocol = 0
	Protocol_PROTOCOL_TCP         Protocol = 1
	Protocol_PROTOCOL_UDP         Protocol = 2
	Protocol_PROTOCOL_ANY         Protocol = 3
)

// Enum value maps for Protocol.
var (
	Protocol_name = map[int32]string{
		0: "PROTOCOL_UNSPECIFIED",
		1: "PROTOCOL_TCP",
		2: "PROTOCOL_UDP",
		3: "PROTOCOL_ANY",
	}
	Protocol_value = map[string]int32{
		"PROTOCOL_UNSPECIFIED": 0,
		"PROTOCOL_TCP":         1,
		"PROTOCOL_UDP":         2,
		"PROTOCOL_ANY":         3,
	}
)

func (x Protocol) Enum() *Protocol {
	p := new(Protocol)
	*p = x
	return p
}

func (x Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_yusui_agent_v1_agent_proto_enumTypes[3].Descriptor()
}

func (Protocol) Type() protoreflect.EnumType {
	return &file_yusui_agent_v1_agent_proto_enumTypes[3]
}

func (x Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Protocol.Descriptor instead.
func (Protocol) EnumDescriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectCode   string                 `protobuf:"bytes,1,opt,name=project_code,json=projectCode,proto3" json:"project_code,omitempty"`
	NetbirdPeerId string                 `protobuf:"bytes,2,opt,name=netbird_peer_id,json=netbirdPeerId,proto3" json:"netbird_peer_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	RegisterToken string                 `protobuf:"bytes,5,opt,name=register_token,json=registerToken,proto3" json:"register_token,omitempty"` // one-time, issued by Server at install (1h)
	Csr           []byte                 `protobuf:"bytes,6,opt,name=csr,proto3" json:"csr,omitempty"`                                          // mTLS client CSR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetProjectCode() string {
	if x != nil {
		return x.ProjectCode
	}
	return ""
}

func (x *RegisterRequest) GetNetbirdPeerId() string {
	if x != nil {
		return x.NetbirdPeerId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetRegisterToken() string {
	if x != nil {
		return x.RegisterToken
	}
	return ""
}

func (x *RegisterRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SignedCert    []byte                 `protobuf:"bytes,2,opt,name=signed_cert,json=signedCert,proto3" json:"signed_cert,omitempty"` // Server CA-signed cert (90d)
	CaCert        []byte                 `protobuf:"bytes,3,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	SessionToken  string                 `protobuf:"bytes,4,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Config        *ControlConfig         `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetSignedCert() []byte {
	if x != nil {
		return x.SignedCert
	}
	return nil
}

func (x *RegisterResponse) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *RegisterResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterResponse) GetConfig() *ControlConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ControlConfig struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	HeartbeatSec         uint32                 `protobuf:"varint,1,opt,name=heartbeat_sec,json=heartbeatSec,proto3" json:"heartbeat_sec,omitempty"`                           // default 10
	FreezeAfterSec       uint32                 `protobuf:"varint,2,opt,name=freeze_after_sec,json=freezeAfterSec,proto3" json:"freeze_after_sec,omitempty"`                   // default 60
	ReconcileIntervalSec uint32                 `protobuf:"varint,3,opt,name=reconcile_interval_sec,json=reconcileIntervalSec,proto3" json:"reconcile_interval_sec,omitempty"` // default 300
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ControlConfig) Reset() {
	*x = ControlConfig{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlConfig) ProtoMessage() {}

func (x *ControlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlConfig.ProtoReflect.Descriptor instead.
func (*ControlConfig) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ControlConfig) GetHeartbeatSec() uint32 {
	if x != nil {
		return x.HeartbeatSec
	}
	return 0
}

func (x *ControlConfig) GetFreezeAfterSec() uint32 {
	if x != nil {
		return x.FreezeAfterSec
	}
	return 0
}

func (x *ControlConfig) GetReconcileIntervalSec() uint32 {
	if x != nil {
		return x.ReconcileIntervalSec
	}
	return 0
}

// ---- upstream (Agent -> Server) ----
type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_Ack
	//	*AgentToServer_RuleEvent
	//	*AgentToServer_AssetReport
	//	*AgentToServer_ReconcileResp
	Msg           isAgentToServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentToServer) GetMsg() isAgentToServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetAck() *AckCommand {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *AgentToServer) GetRuleEvent() *RuleEvent {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_RuleEvent); ok {
			return x.RuleEvent
		}
	}
	return nil
}

func (x *AgentToServer) GetAssetReport() *AssetReport {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_AssetReport); ok {
			return x.AssetReport
		}
	}
	return nil
}

func (x *AgentToServer) GetReconcileResp() *ReconcileResponse {
	if x != nil {
		if x, ok := x.Msg.(*AgentToServer_ReconcileResp); ok {
			return x.ReconcileResp
		}
	}
	return nil
}

type isAgentToServer_Msg interface {
	isAgentToServer_Msg()
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_Ack struct {
	Ack *AckCommand `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type AgentToServer_RuleEvent struct {
	RuleEvent *RuleEvent `protobuf:"bytes,3,opt,name=rule_event,json=ruleEvent,proto3,oneof"`
}

type AgentToServer_AssetReport struct {
	AssetReport *AssetReport `protobuf:"bytes,4,opt,name=asset_report,json=assetReport,proto3,oneof"`
}

type AgentToServer_ReconcileResp struct {
	ReconcileResp *ReconcileResponse `protobuf:"bytes,5,opt,name=reconcile_resp,json=reconcileResp,proto3,oneof"`
}

func (*AgentToServer_Heartbeat) isAgentToServer_Msg() {}

func (*AgentToServer_Ack) isAgentToServer_Msg() {}

func (*AgentToServer_RuleEvent) isAgentToServer_Msg() {}

func (*AgentToServer_AssetReport) isAgentToServer_Msg() {}

func (*AgentToServer_ReconcileResp) isAgentToServer_Msg() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=yusui.agent.v1.AgentStatus" json:"status,omitempty"`
	ActiveRules   uint64                 `protobuf:"varint,3,opt,name=active_rules,json=activeRules,proto3" json:"active_rules,omitempty"`
	NetbirdStatus string                 `protobuf:"bytes,4,opt,name=netbird_status,json=netbirdStatus,proto3" json:"netbird_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *Heartbeat) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Heartbeat) GetActiveRules() uint64 {
	if x != nil {
		return x.ActiveRules
	}
	return 0
}

func (x *Heartbeat) GetNetbirdStatus() string {
	if x != nil {
		return x.NetbirdStatus
	}
	return ""
}

type AckCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Result    AckResult              `protobuf:"varint,2,opt,name=result,proto3,enum=yusui.agent.v1.AckResult" json:"result,omitempty"`
	ErrorMsg  string                 `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// draft10: on a successful ApplyRule, the Agent's userspace forwarder reports
	// the overlay address (host:port) the Server should dial to reach the asset.
	// Empty for the kernel nft enforcer (Server dials the asset IP directly).
	ForwardAddr   string `protobuf:"bytes,4,opt,name=forward_addr,json=forwardAddr,proto3" json:"forward_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommand) Reset() {
	*x = AckCommand{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommand) ProtoMessage() {}

func (x *AckCommand) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommand.ProtoReflect.Descriptor instead.
func (*AckCommand) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AckCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AckCommand) GetResult() AckResult {
	if x != nil {
		return x.Result
	}
	return AckResult_ACK_RESULT_UNSPECIFIED
}

func (x *AckCommand) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *AckCommand) GetForwardAddr() string {
	if x != nil {
		return x.ForwardAddr
	}
	return ""
}

type RuleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Kind          RuleEventKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=yusui.agent.v1.RuleEventKind" json:"kind,omitempty"`
	PacketCount   uint64                 `protobuf:"varint,3,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleEvent) Reset() {
	*x = RuleEvent{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEvent) ProtoMessage() {}

func (x *RuleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEvent.ProtoReflect.Descriptor instead.
func (*RuleEvent) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *RuleEvent) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleEvent) GetKind() RuleEventKind {
	if x != nil {
		return x.Kind
	}
	return RuleEventKind_RULE_EVENT_KIND_UNSPECIFIED
}

func (x *RuleEvent) GetPacketCount() uint64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

func (x *RuleEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type AssetReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*AssetCandidate      `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetReport) Reset() {
	*x = AssetReport{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetReport) ProtoMessage() {}

func (x *AssetReport) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetReport.ProtoReflect.Descriptor instead.
func (*AssetReport) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AssetReport) GetCandidates() []*AssetCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type AssetCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	HostnameGuess string                 `protobuf:"bytes,3,opt,name=hostname_guess,json=hostnameGuess,proto3" json:"hostname_guess,omitempty"`
	PortsSeen     []uint32               `protobuf:"varint,4,rep,packed,name=ports_seen,json=portsSeen,proto3" json:"ports_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetCandidate) Reset() {
	*x = AssetCandidate{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetCandidate) ProtoMessage() {}

func (x *AssetCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetCandidate.ProtoReflect.Descriptor instead.
func (*AssetCandidate) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AssetCandidate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AssetCandidate) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AssetCandidate) GetHostnameGuess() string {
	if x != nil {
		return x.HostnameGuess
	}
	return ""
}

func (x *AssetCandidate) GetPortsSeen() []uint32 {
	if x != nil {
		return x.PortsSeen
	}
	return nil
}

// ---- downstream (Server -> Agent) ----
type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerToAgent_Apply
	//	*ServerToAgent_Revoke
	//	*ServerToAgent_Reconcile
	//	*ServerToAgent_Config
	//	*ServerToAgent_Drain
	Msg           isServerToAgent_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ServerToAgent) GetMsg() isServerToAgent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerToAgent) GetApply() *ApplyRule {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *ServerToAgent) GetRevoke() *RevokeRule {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Revoke); ok {
			return x.Revoke
		}
	}
	return nil
}

func (x *ServerToAgent) GetReconcile() *ReconcileRequest {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Reconcile); ok {
			return x.Reconcile
		}
	}
	return nil
}

func (x *ServerToAgent) GetConfig() *UpdateConfig {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ServerToAgent) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Msg.(*ServerToAgent_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

type isServerToAgent_Msg interface {
	isServerToAgent_Msg()
}

type ServerToAgent_Apply struct {
	Apply *ApplyRule `protobuf:"bytes,1,opt,name=apply,proto3,oneof"`
}

type ServerToAgent_Revoke struct {
	Revoke *RevokeRule `protobuf:"bytes,2,opt,name=revoke,proto3,oneof"`
}

type ServerToAgent_Reconcile struct {
	Reconcile *ReconcileRequest `protobuf:"bytes,3,opt,name=reconcile,proto3,oneof"`
}

type ServerToAgent_Config struct {
	Config *UpdateConfig `protobuf:"bytes,4,opt,name=config,proto3,oneof"`
}

type ServerToAgent_Drain struct {
	Drain *Drain `protobuf:"bytes,5,opt,name=drain,proto3,oneof"`
}

func (*ServerToAgent_Apply) isServerToAgent_Msg() {}

func (*ServerToAgent_Revoke) isServerToAgent_Msg() {}

func (*ServerToAgent_Reconcile) isServerToAgent_Msg() {}

func (*ServerToAgent_Config) isServerToAgent_Msg() {}

func (*ServerToAgent_Drain) isServerToAgent_Msg() {}

type ApplyRule struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RuleId    string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // YuSui-global; written into the nft element comment
	TicketId  string                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	// Deprecated: Marked as deprecated in yusui/agent/v1/agent.proto.
	SrcPeerIp     string                 `protobuf:"bytes,4,opt,name=src_peer_ip,json=srcPeerIp,proto3" json:"src_peer_ip,omitempty"`    // pre-draft7; kept for N-1 agents
	SrcPeerIps    []string               `protobuf:"bytes,9,rep,name=src_peer_ips,json=srcPeerIps,proto3" json:"src_peer_ips,omitempty"` // draft7: multi-source (HA server)
	DstIp         string                 `protobuf:"bytes,5,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,6,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Proto         Protocol               `protobuf:"varint,7,opt,name=proto,proto3,enum=yusui.agent.v1.Protocol" json:"proto,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRule) Reset() {
	*x = ApplyRule{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRule) ProtoMessage() {}

func (x *ApplyRule) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRule.ProtoReflect.Descriptor instead.
func (*ApplyRule) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ApplyRule) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ApplyRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ApplyRule) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// Deprecated: Marked as deprecated in yusui/agent/v1/agent.proto.
func (x *ApplyRule) GetSrcPeerIp() string {
	if x != nil {
		return x.SrcPeerIp
	}
	return ""
}

func (x *ApplyRule) GetSrcPeerIps() []string {
	if x != nil {
		return x.SrcPeerIps
	}
	return nil
}

func (x *ApplyRule) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *ApplyRule) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *ApplyRule) GetProto() Protocol {
	if x != nil {
		return x.Proto
	}
	return Protocol_PROTOCOL_UNSPECIFIED
}

func (x *ApplyRule) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RevokeRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRule) Reset() {
	*x = RevokeRule{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRule) ProtoMessage() {}

func (x *RevokeRule) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRule.ProtoReflect.Descriptor instead.
func (*RevokeRule) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeRule) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *RevokeRule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RevokeRule) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReconcileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ReconcileRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type ReconcileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	ActiveRuleIds []string               `protobuf:"bytes,2,rep,name=active_rule_ids,json=activeRuleIds,proto3" json:"active_rule_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ReconcileResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *ReconcileResponse) GetActiveRuleIds() []string {
	if x != nil {
		return x.ActiveRuleIds
	}
	return nil
}

type UpdateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Config        *ControlConfig         `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfig) Reset() {
	*x = UpdateConfig{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfig) ProtoMessage() {}

func (x *UpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfig.ProtoReflect.Descriptor instead.
func (*UpdateConfig) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateConfig) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *UpdateConfig) GetConfig() *ControlConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	GracefulSec   uint32                 `protobuf:"varint,2,opt,name=graceful_sec,json=gracefulSec,proto3" json:"graceful_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_yusui_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_yusui_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *Drain) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Drain) GetGracefulSec() uint32 {
	if x != nil {
		return x.GracefulSec
	}
	return 0
}

var File_yusui_agent_v1_agent_proto protoreflect.FileDescriptor

const file_yusui_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1ayusui/agent/v1/agent.proto\x12\x0eyusui.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x01\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fproject_code\x18\x01 \x01(\tR\vprojectCode\x12&\n" +
	"\x0fnetbird_peer_id\x18\x02 \x01(\tR\rnetbirdPeerId\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12%\n" +
	"\x0eregister_token\x18\x05 \x01(\tR\rregisterToken\x12\x10\n" +
	"\x03csr\x18\x06 \x01(\fR\x03csr\"\xc3\x01\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1f\n" +
	"\vsigned_cert\x18\x02 \x01(\fR\n" +
	"signedCert\x12\x17\n" +
	"\aca_cert\x18\x03 \x01(\fR\x06caCert\x12#\n" +
	"\rsession_token\x18\x04 \x01(\tR\fsessionToken\x125\n" +
	"\x06config\x18\x05 \x01(\v2\x1d.yusui.agent.v1.ControlConfigR\x06config\"\x94\x01\n" +
	"\rControlConfig\x12#\n" +
	"\rheartbeat_sec\x18\x01 \x01(\rR\fheartbeatSec\x12(\n" +
	"\x10freeze_after_sec\x18\x02 \x01(\rR\x0efreezeAfterSec\x124\n" +
	"\x16reconcile_interval_sec\x18\x03 \x01(\rR\x14reconcileIntervalSec\"\xcb\x02\n" +
	"\rAgentToServer\x129\n" +
	"\theartbeat\x18\x01 \x01(\v2\x19.yusui.agent.v1.HeartbeatH\x00R\theartbeat\x12.\n" +
	"\x03ack\x18\x02 \x01(\v2\x1a.yusui.agent.v1.AckCommandH\x00R\x03ack\x12:\n" +
	"\n" +
	"rule_event\x18\x03 \x01(\v2\x19.yusui.agent.v1.RuleEventH\x00R\truleEvent\x12@\n" +
	"\fasset_report\x18\x04 \x01(\v2\x1b.yusui.agent.v1.AssetReportH\x00R\vassetReport\x12J\n" +
	"\x0ereconcile_resp\x18\x05 \x01(\v2!.yusui.agent.v1.ReconcileResponseH\x00R\rreconcileRespB\x05\n" +
	"\x03msg\"\xb6\x01\n" +
	"\tHeartbeat\x12*\n" +
	"\x02ts\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.yusui.agent.v1.AgentStatusR\x06status\x12!\n" +
	"\factive_rules\x18\x03 \x01(\x04R\vactiveRules\x12%\n" +
	"\x0enetbird_status\x18\x04 \x01(\tR\rnetbirdStatus\"\x9e\x01\n" +
	"\n" +
	"AckCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x121\n" +
	"\x06result\x18\x02 \x01(\x0e2\x19.yusui.agent.v1.AckResultR\x06result\x12\x1b\n" +
	"\terror_msg\x18\x03 \x01(\tR\berrorMsg\x12!\n" +
	"\fforward_addr\x18\x04 \x01(\tR\vforwardAddr\"\xa6\x01\n" +
	"\tRuleEvent\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x121\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1d.yusui.agent.v1.RuleEventKindR\x04kind\x12!\n" +
	"\fpacket_count\x18\x03 \x01(\x04R\vpacketCount\x12*\n" +
	"\x02at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"M\n" +
	"\vAssetReport\x12>\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x1e.yusui.agent.v1.AssetCandidateR\n" +
	"candidates\"x\n" +
	"\x0eAssetCandidate\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12%\n" +
	"\x0ehostname_guess\x18\x03 \x01(\tR\rhostnameGuess\x12\x1d\n" +
	"\n" +
	"ports_seen\x18\x04 \x03(\rR\tportsSeen\"\xa8\x02\n" +
	"\rServerToAgent\x121\n" +
	"\x05apply\x18\x01 \x01(\v2\x19.yusui.agent.v1.ApplyRuleH\x00R\x05apply\x124\n" +
	"\x06revoke\x18\x02 \x01(\v2\x1a.yusui.agent.v1.RevokeRuleH\x00R\x06revoke\x12@\n" +
	"\treconcile\x18\x03 \x01(\v2 .yusui.agent.v1.ReconcileRequestH\x00R\treconcile\x126\n" +
	"\x06config\x18\x04 \x01(\v2\x1c.yusui.agent.v1.UpdateConfigH\x00R\x06config\x12-\n" +
	"\x05drain\x18\x05 \x01(\v2\x15.yusui.agent.v1.DrainH\x00R\x05drainB\x05\n" +
	"\x03msg\"\xc3\x02\n" +
	"\tApplyRule\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x12\"\n" +
	"\vsrc_peer_ip\x18\x04 \x01(\tB\x02\x18\x01R\tsrcPeerIp\x12 \n" +
	"\fsrc_peer_ips\x18\t \x03(\tR\n" +
	"srcPeerIps\x12\x15\n" +
	"\x06dst_ip\x18\x05 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x06 \x01(\rR\adstPort\x12.\n" +
	"\x05proto\x18\a \x01(\x0e2\x18.yusui.agent.v1.ProtocolR\x05proto\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\\\n" +
	"\n" +
	"RevokeRule\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"1\n" +
	"\x10ReconcileRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"Z\n" +
	"\x11ReconcileResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12&\n" +
	"\x0factive_rule_ids\x18\x02 \x03(\tR\ractiveRuleIds\"d\n" +
	"\fUpdateConfig\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x125\n" +
	"\x06config\x18\x02 \x01(\v2\x1d.yusui.agent.v1.ControlConfigR\x06config\"I\n" +
	"\x05Drain\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12!\n" +
	"\fgraceful_sec\x18\x02 \x01(\rR\vgracefulSec*w\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12AGENT_STATUS_READY\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_DEGRADED\x10\x02\x12\x17\n" +
	"\x13AGENT_STATUS_FROZEN\x10\x03*\x81\x01\n" +
	"\tAckResult\x12\x1a\n" +
	"\x16ACK_RESULT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACK_RESULT_OK\x10\x01\x12\x15\n" +
	"\x11ACK_RESULT_FAILED\x10\x02\x12\x16\n" +
	"\x12ACK_RESULT_PARTIAL\x10\x03\x12\x16\n" +
	"\x12ACK_RESULT_SKIPPED\x10\x04*\xca\x01\n" +
	"\rRuleEventKind\x12\x1f\n" +
	"\x1bRULE_EVENT_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RULE_EVENT_KIND_APPLIED\x10\x01\x12\x1b\n" +
	"\x17RULE_EVENT_KIND_REVOKED\x10\x02\x12!\n" +
	"\x1dRULE_EVENT_KIND_EXPIRED_LOCAL\x10\x03\x12\x1d\n" +
	"\x19RULE_EVENT_KIND_HIT_FIRST\x10\x04\x12\x1c\n" +
	"\x18RULE_EVENT_KIND_HIT_LAST\x10\x05*Z\n" +
	"\bProtocol\x12\x18\n" +
	"\x14PROTOCOL_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPROTOCOL_TCP\x10\x01\x12\x10\n" +
	"\fPROTOCOL_UDP\x10\x02\x12\x10\n" +
	"\fPROTOCOL_ANY\x10\x032\xaa\x01\n" +
	"\fAgentControl\x12M\n" +
	"\bRegister\x12\x1f.yusui.agent.v1.RegisterRequest\x1a .yusui.agent.v1.RegisterResponse\x12K\n" +
	"\aControl\x12\x1d.yusui.agent.v1.AgentToServer\x1a\x1d.yusui.agent.v1.ServerToAgent(\x010\x01B;Z9github.com/catundercar/yusui/proto/yusui/agent/v1;agentv1b\x06proto3"

var (
	file_yusui_agent_v1_agent_proto_rawDescOnce sync.Once
	file_yusui_agent_v1_agent_proto_rawDescData []byte
)

func file_yusui_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_yusui_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_yusui_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yusui_agent_v1_agent_proto_rawDesc), len(file_yusui_agent_v1_agent_proto_rawDesc)))
	})
	return file_yusui_agent_v1_agent_proto_rawDescData
}

var file_yusui_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_yusui_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_yusui_agent_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),              // 0: yusui.agent.v1.AgentStatus
	(AckResult)(0),                // 1: yusui.agent.v1.AckResult
	(RuleEventKind)(0),            // 2: yusui.agent.v1.RuleEventKind
	(Protocol)(0),                 // 3: yusui.agent.v1.Protocol
	(*RegisterRequest)(nil),       // 4: yusui.agent.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 5: yusui.agent.v1.RegisterResponse
	(*ControlConfig)(nil),         // 6: yusui.agent.v1.ControlConfig
	(*AgentToServer)(nil),         // 7: yusui.agent.v1.AgentToServer
	(*Heartbeat)(nil),             // 8: yusui.agent.v1.Heartbeat
	(*AckCommand)(nil),            // 9: yusui.agent.v1.AckCommand
	(*RuleEvent)(nil),             // 10: yusui.agent.v1.RuleEvent
	(*AssetReport)(nil),           // 11: yusui.agent.v1.AssetReport
	(*AssetCandidate)(nil),        // 12: yusui.agent.v1.AssetCandidate
	(*ServerToAgent)(nil),         // 13: yusui.agent.v1.ServerToAgent
	(*ApplyRule)(nil),             // 14: yusui.agent.v1.ApplyRule
	(*RevokeRule)(nil),            // 15: yusui.agent.v1.RevokeRule
	(*ReconcileRequest)(nil),      // 16: yusui.agent.v1.ReconcileRequest
	(*ReconcileResponse)(nil),     // 17: yusui.agent.v1.ReconcileResponse
	(*UpdateConfig)(nil),          // 18: yusui.agent.v1.UpdateConfig
	(*Drain)(nil),                 // 19: yusui.agent.v1.Drain
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_yusui_agent_v1_agent_proto_depIdxs = []int32{
	6,  // 0: yusui.agent.v1.RegisterResponse.config:type_name -> yusui.agent.v1.ControlConfig
	8,  // 1: yusui.agent.v1.AgentToServer.heartbeat:type_name -> yusui.agent.v1.Heartbeat
	9,  // 2: yusui.agent.v1.AgentToServer.ack:type_name -> yusui.agent.v1.AckCommand
	10, // 3: yusui.agent.v1.AgentToServer.rule_event:type_name -> yusui.agent.v1.RuleEvent
	11, // 4: yusui.agent.v1.AgentToServer.asset_report:type_name -> yusui.agent.v1.AssetReport
	17, // 5: yusui.agent.v1.AgentToServer.reconcile_resp:type_name -> yusui.agent.v1.ReconcileResponse
	20, // 6: yusui.agent.v1.Heartbeat.ts:type_name -> google.protobuf.Timestamp
	0,  // 7: yusui.agent.v1.Heartbeat.status:type_name -> yusui.agent.v1.AgentStatus
	1,  // 8: yusui.agent.v1.AckCommand.result:type_name -> yusui.agent.v1.AckResult
	2,  // 9: yusui.agent.v1.RuleEvent.kind:type_name -> yusui.agent.v1.RuleEventKind
	20, // 10: yusui.agent.v1.RuleEvent.at:type_name -> google.protobuf.Timestamp
	12, // 11: yusui.agent.v1.AssetReport.candidates:type_name -> yusui.agent.v1.AssetCandidate
	14, // 12: yusui.agent.v1.ServerToAgent.apply:type_name -> yusui.agent.v1.ApplyRule
	15, // 13: yusui.agent.v1.ServerToAgent.revoke:type_name -> yusui.agent.v1.RevokeRule
	16, // 14: yusui.agent.v1.ServerToAgent.reconcile:type_name -> yusui.agent.v1.ReconcileRequest
	18, // 15: yusui.agent.v1.ServerToAgent.config:type_name -> yusui.agent.v1.UpdateConfig
	19, // 16: yusui.agent.v1.ServerToAgent.drain:type_name -> yusui.agent.v1.Drain
	3,  // 17: yusui.agent.v1.ApplyRule.proto:type_name -> yusui.agent.v1.Protocol
	20, // 18: yusui.agent.v1.ApplyRule.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 19: yusui.agent.v1.UpdateConfig.config:type_name -> yusui.agent.v1.ControlConfig
	4,  // 20: yusui.agent.v1.AgentControl.Register:input_type -> yusui.agent.v1.RegisterRequest
	7,  // 21: yusui.agent.v1.AgentControl.Control:input_type -> yusui.agent.v1.AgentToServer
	5,  // 22: yusui.agent.v1.AgentControl.Register:output_type -> yusui.agent.v1.RegisterResponse
	13, // 23: yusui.agent.v1.AgentControl.Control:output_type -> yusui.agent.v1.ServerToAgent
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_yusui_agent_v1_agent_proto_init() }
func file_yusui_agent_v1_agent_proto_init() {
	if File_yusui_agent_v1_agent_proto != nil {
		return
	}
	file_yusui_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_Ack)(nil),
		(*AgentToServer_RuleEvent)(nil),
		(*AgentToServer_AssetReport)(nil),
		(*AgentToServer_ReconcileResp)(nil),
	}
	file_yusui_agent_v1_agent_proto_msgTypes[9].OneofWrappers = []any{
		(*ServerToAgent_Apply)(nil),
		(*ServerToAgent_Revoke)(nil),
		(*ServerToAgent_Reconcile)(nil),
		(*ServerToAgent_Config)(nil),
		(*ServerToAgent_Drain)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yusui_agent_v1_agent_proto_rawDesc), len(file_yusui_agent_v1_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yusui_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_yusui_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_yusui_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_yusui_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_yusui_agent_v1_agent_proto = out.File
	file_yusui_agent_v1_agent_proto_goTypes = nil
	file_yusui_agent_v1_agent_proto_depIdxs = nil
}
